- name: Deploy PrivateBin from an Ansible template
  kubernetes.core.k8s:
    state: present
    definition: "{{ item }}"
  with_items: >-
    {{ 
      lookup('template', 'k8s-template-privatebin.yml') |
      from_yaml_all 
    }}
